classes = [
    {"darwin_id": None, "name": "tench Tinca tinca", "type": "tag"},
    {"darwin_id": None, "name": "goldfish Carassius auratus", "type": "tag"},
    {
        "darwin_id": None,
        "name": "great white shark white shark man-eater man-eating shark Carcharodon carcharias",
        "type": "tag",
    },
    {"darwin_id": None, "name": "tiger shark Galeocerdo cuvieri", "type": "tag"},
    {"darwin_id": None, "name": "hammerhead hammerhead shark", "type": "tag"},
    {"darwin_id": None, "name": "electric ray crampfish numbfish torpedo", "type": "tag"},
    {"darwin_id": None, "name": "stingray", "type": "tag"},
    {"darwin_id": None, "name": "cock", "type": "tag"},
    {"darwin_id": None, "name": "hen", "type": "tag"},
    {"darwin_id": None, "name": "ostrich Struthio camelus", "type": "tag"},
    {"darwin_id": None, "name": "brambling Fringilla montifringilla", "type": "tag"},
    {"darwin_id": None, "name": "goldfinch Carduelis carduelis", "type": "tag"},
    {"darwin_id": None, "name": "house finch linnet Carpodacus mexicanus", "type": "tag"},
    {"darwin_id": None, "name": "junco snowbird", "type": "tag"},
    {"darwin_id": None, "name": "indigo bunting indigo finch indigo bird Passerina cyanea", "type": "tag"},
    {"darwin_id": None, "name": "robin American robin Turdus migratorius", "type": "tag"},
    {"darwin_id": None, "name": "bulbul", "type": "tag"},
    {"darwin_id": None, "name": "jay", "type": "tag"},
    {"darwin_id": None, "name": "magpie", "type": "tag"},
    {"darwin_id": None, "name": "chickadee", "type": "tag"},
    {"darwin_id": None, "name": "water ouzel dipper", "type": "tag"},
    {"darwin_id": None, "name": "kite", "type": "tag"},
    {"darwin_id": None, "name": "bald eagle American eagle Haliaeetus leucocephalus", "type": "tag"},
    {"darwin_id": None, "name": "vulture", "type": "tag"},
    {"darwin_id": None, "name": "great grey owl great gray owl Strix nebulosa", "type": "tag"},
    {"darwin_id": None, "name": "European fire salamander Salamandra salamandra", "type": "tag"},
    {"darwin_id": None, "name": "common newt Triturus vulgaris", "type": "tag"},
    {"darwin_id": None, "name": "eft", "type": "tag"},
    {"darwin_id": None, "name": "spotted salamander Ambystoma maculatum", "type": "tag"},
    {"darwin_id": None, "name": "axolotl mud puppy Ambystoma mexicanum", "type": "tag"},
    {"darwin_id": None, "name": "bullfrog Rana catesbeiana", "type": "tag"},
    {"darwin_id": None, "name": "tree frog tree-frog", "type": "tag"},
    {"darwin_id": None, "name": "tailed frog bell toad ribbed toad tailed toad Ascaphus trui", "type": "tag"},
    {"darwin_id": None, "name": "loggerhead loggerhead turtle Caretta caretta", "type": "tag"},
    {"darwin_id": None, "name": "leatherback turtle leatherback leathery turtle Dermochelys coriacea", "type": "tag"},
    {"darwin_id": None, "name": "mud turtle", "type": "tag"},
    {"darwin_id": None, "name": "terrapin", "type": "tag"},
    {"darwin_id": None, "name": "box turtle box tortoise", "type": "tag"},
    {"darwin_id": None, "name": "banded gecko", "type": "tag"},
    {"darwin_id": None, "name": "common iguana iguana Iguana iguana", "type": "tag"},
    {"darwin_id": None, "name": "American chameleon anole Anolis carolinensis", "type": "tag"},
    {"darwin_id": None, "name": "whiptail whiptail lizard", "type": "tag"},
    {"darwin_id": None, "name": "agama", "type": "tag"},
    {"darwin_id": None, "name": "frilled lizard Chlamydosaurus kingi", "type": "tag"},
    {"darwin_id": None, "name": "alligator lizard", "type": "tag"},
    {"darwin_id": None, "name": "Gila monster Heloderma suspectum", "type": "tag"},
    {"darwin_id": None, "name": "green lizard Lacerta viridis", "type": "tag"},
    {"darwin_id": None, "name": "African chameleon Chamaeleo chamaeleon", "type": "tag"},
    {
        "darwin_id": None,
        "name": "Komodo dragon Komodo lizard dragon lizard giant lizard Varanus komodoensis",
        "type": "tag",
    },
    {"darwin_id": None, "name": "African crocodile Nile crocodile Crocodylus niloticus", "type": "tag"},
    {"darwin_id": None, "name": "American alligator Alligator mississipiensis", "type": "tag"},
    {"darwin_id": None, "name": "triceratops", "type": "tag"},
    {"darwin_id": None, "name": "thunder snake worm snake Carphophis amoenus", "type": "tag"},
    {"darwin_id": None, "name": "ringneck snake ring-necked snake ring snake", "type": "tag"},
    {"darwin_id": None, "name": "hognose snake puff adder sand viper", "type": "tag"},
    {"darwin_id": None, "name": "green snake grass snake", "type": "tag"},
    {"darwin_id": None, "name": "king snake kingsnake", "type": "tag"},
    {"darwin_id": None, "name": "garter snake grass snake", "type": "tag"},
    {"darwin_id": None, "name": "water snake", "type": "tag"},
    {"darwin_id": None, "name": "vine snake", "type": "tag"},
    {"darwin_id": None, "name": "night snake Hypsiglena torquata", "type": "tag"},
    {"darwin_id": None, "name": "boa constrictor Constrictor constrictor", "type": "tag"},
    {"darwin_id": None, "name": "rock python rock snake Python sebae", "type": "tag"},
    {"darwin_id": None, "name": "Indian cobra Naja naja", "type": "tag"},
    {"darwin_id": None, "name": "green mamba", "type": "tag"},
    {"darwin_id": None, "name": "sea snake", "type": "tag"},
    {"darwin_id": None, "name": "horned viper cerastes sand viper horned asp Cerastes cornutus", "type": "tag"},
    {"darwin_id": None, "name": "diamondback diamondback rattlesnake Crotalus adamanteus", "type": "tag"},
    {"darwin_id": None, "name": "sidewinder horned rattlesnake Crotalus cerastes", "type": "tag"},
    {"darwin_id": None, "name": "trilobite", "type": "tag"},
    {"darwin_id": None, "name": "harvestman daddy longlegs Phalangium opilio", "type": "tag"},
    {"darwin_id": None, "name": "scorpion", "type": "tag"},
    {"darwin_id": None, "name": "black and gold garden spider Argiope aurantia", "type": "tag"},
    {"darwin_id": None, "name": "barn spider Araneus cavaticus", "type": "tag"},
    {"darwin_id": None, "name": "garden spider Aranea diademata", "type": "tag"},
    {"darwin_id": None, "name": "black widow Latrodectus mactans", "type": "tag"},
    {"darwin_id": None, "name": "tarantula", "type": "tag"},
    {"darwin_id": None, "name": "wolf spider hunting spider", "type": "tag"},
    {"darwin_id": None, "name": "tick", "type": "tag"},
    {"darwin_id": None, "name": "centipede", "type": "tag"},
    {"darwin_id": None, "name": "black grouse", "type": "tag"},
    {"darwin_id": None, "name": "ptarmigan", "type": "tag"},
    {"darwin_id": None, "name": "ruffed grouse partridge Bonasa umbellus", "type": "tag"},
    {"darwin_id": None, "name": "prairie chicken prairie grouse prairie fowl", "type": "tag"},
    {"darwin_id": None, "name": "peacock", "type": "tag"},
    {"darwin_id": None, "name": "quail", "type": "tag"},
    {"darwin_id": None, "name": "partridge", "type": "tag"},
    {"darwin_id": None, "name": "African grey African gray Psittacus erithacus", "type": "tag"},
    {"darwin_id": None, "name": "macaw", "type": "tag"},
    {"darwin_id": None, "name": "sulphur-crested cockatoo Kakatoe galerita Cacatua galerita", "type": "tag"},
    {"darwin_id": None, "name": "lorikeet", "type": "tag"},
    {"darwin_id": None, "name": "coucal", "type": "tag"},
    {"darwin_id": None, "name": "bee eater", "type": "tag"},
    {"darwin_id": None, "name": "hornbill", "type": "tag"},
    {"darwin_id": None, "name": "hummingbird", "type": "tag"},
    {"darwin_id": None, "name": "jacamar", "type": "tag"},
    {"darwin_id": None, "name": "toucan", "type": "tag"},
    {"darwin_id": None, "name": "drake", "type": "tag"},
    {"darwin_id": None, "name": "red-breasted merganser Mergus serrator", "type": "tag"},
    {"darwin_id": None, "name": "goose", "type": "tag"},
    {"darwin_id": None, "name": "black swan Cygnus atratus", "type": "tag"},
    {"darwin_id": None, "name": "tusker", "type": "tag"},
    {"darwin_id": None, "name": "echidna spiny anteater anteater", "type": "tag"},
    {
        "darwin_id": None,
        "name": "platypus duckbill duckbilled platypus duck-billed platypus Ornithorhynchus anatinus",
        "type": "tag",
    },
    {"darwin_id": None, "name": "wallaby brush kangaroo", "type": "tag"},
    {"darwin_id": None, "name": "koala koala bear kangaroo bear native bear Phascolarctos cinereus", "type": "tag"},
    {"darwin_id": None, "name": "wombat", "type": "tag"},
    {"darwin_id": None, "name": "jellyfish", "type": "tag"},
    {"darwin_id": None, "name": "sea anemone anemone", "type": "tag"},
    {"darwin_id": None, "name": "brain coral", "type": "tag"},
    {"darwin_id": None, "name": "flatworm platyhelminth", "type": "tag"},
    {"darwin_id": None, "name": "nematode nematode worm roundworm", "type": "tag"},
    {"darwin_id": None, "name": "conch", "type": "tag"},
    {"darwin_id": None, "name": "snail", "type": "tag"},
    {"darwin_id": None, "name": "slug", "type": "tag"},
    {"darwin_id": None, "name": "sea slug nudibranch", "type": "tag"},
    {"darwin_id": None, "name": "chiton coat-of-mail shell sea cradle polyplacophore", "type": "tag"},
    {"darwin_id": None, "name": "chambered nautilus pearly nautilus nautilus", "type": "tag"},
    {"darwin_id": None, "name": "Dungeness crab Cancer magister", "type": "tag"},
    {"darwin_id": None, "name": "rock crab Cancer irroratus", "type": "tag"},
    {"darwin_id": None, "name": "fiddler crab", "type": "tag"},
    {
        "darwin_id": None,
        "name": "king crab Alaska crab Alaskan king crab Alaska king crab Paralithodes camtschatica",
        "type": "tag",
    },
    {"darwin_id": None, "name": "American lobster Northern lobster Maine lobster Homarus americanus", "type": "tag"},
    {"darwin_id": None, "name": "spiny lobster langouste rock lobster crawfish crayfish sea crawfish", "type": "tag"},
    {"darwin_id": None, "name": "crayfish crawfish crawdad crawdaddy", "type": "tag"},
    {"darwin_id": None, "name": "hermit crab", "type": "tag"},
    {"darwin_id": None, "name": "isopod", "type": "tag"},
    {"darwin_id": None, "name": "white stork Ciconia ciconia", "type": "tag"},
    {"darwin_id": None, "name": "black stork Ciconia nigra", "type": "tag"},
    {"darwin_id": None, "name": "spoonbill", "type": "tag"},
    {"darwin_id": None, "name": "flamingo", "type": "tag"},
    {"darwin_id": None, "name": "little blue heron Egretta caerulea", "type": "tag"},
    {"darwin_id": None, "name": "American egret great white heron Egretta albus", "type": "tag"},
    {"darwin_id": None, "name": "bittern", "type": "tag"},
    {"darwin_id": None, "name": "crane", "type": "tag"},
    {"darwin_id": None, "name": "limpkin Aramus pictus", "type": "tag"},
    {"darwin_id": None, "name": "European gallinule Porphyrio porphyrio", "type": "tag"},
    {"darwin_id": None, "name": "American coot marsh hen mud hen water hen Fulica americana", "type": "tag"},
    {"darwin_id": None, "name": "bustard", "type": "tag"},
    {"darwin_id": None, "name": "ruddy turnstone Arenaria interpres", "type": "tag"},
    {"darwin_id": None, "name": "red-backed sandpiper dunlin Erolia alpina", "type": "tag"},
    {"darwin_id": None, "name": "redshank Tringa totanus", "type": "tag"},
    {"darwin_id": None, "name": "dowitcher", "type": "tag"},
    {"darwin_id": None, "name": "oystercatcher oyster catcher", "type": "tag"},
    {"darwin_id": None, "name": "pelican", "type": "tag"},
    {"darwin_id": None, "name": "king penguin Aptenodytes patagonica", "type": "tag"},
    {"darwin_id": None, "name": "albatross mollymawk", "type": "tag"},
    {
        "darwin_id": None,
        "name": "grey whale gray whale devilfish Eschrichtius gibbosus Eschrichtius robustus",
        "type": "tag",
    },
    {"darwin_id": None, "name": "killer whale killer orca grampus sea wolf Orcinus orca", "type": "tag"},
    {"darwin_id": None, "name": "dugong Dugong dugon", "type": "tag"},
    {"darwin_id": None, "name": "sea lion", "type": "tag"},
    {"darwin_id": None, "name": "Chihuahua", "type": "tag"},
    {"darwin_id": None, "name": "Japanese spaniel", "type": "tag"},
    {"darwin_id": None, "name": "Maltese dog Maltese terrier Maltese", "type": "tag"},
    {"darwin_id": None, "name": "Pekinese Pekingese Peke", "type": "tag"},
    {"darwin_id": None, "name": "Shih-Tzu", "type": "tag"},
    {"darwin_id": None, "name": "Blenheim spaniel", "type": "tag"},
    {"darwin_id": None, "name": "papillon", "type": "tag"},
    {"darwin_id": None, "name": "toy terrier", "type": "tag"},
    {"darwin_id": None, "name": "Rhodesian ridgeback", "type": "tag"},
    {"darwin_id": None, "name": "Afghan hound Afghan", "type": "tag"},
    {"darwin_id": None, "name": "basset basset hound", "type": "tag"},
    {"darwin_id": None, "name": "beagle", "type": "tag"},
    {"darwin_id": None, "name": "bloodhound sleuthhound", "type": "tag"},
    {"darwin_id": None, "name": "bluetick", "type": "tag"},
    {"darwin_id": None, "name": "black-and-tan coonhound", "type": "tag"},
    {"darwin_id": None, "name": "Walker hound Walker foxhound", "type": "tag"},
    {"darwin_id": None, "name": "English foxhound", "type": "tag"},
    {"darwin_id": None, "name": "redbone", "type": "tag"},
    {"darwin_id": None, "name": "borzoi Russian wolfhound", "type": "tag"},
    {"darwin_id": None, "name": "Irish wolfhound", "type": "tag"},
    {"darwin_id": None, "name": "Italian greyhound", "type": "tag"},
    {"darwin_id": None, "name": "whippet", "type": "tag"},
    {"darwin_id": None, "name": "Ibizan hound Ibizan Podenco", "type": "tag"},
    {"darwin_id": None, "name": "Norwegian elkhound elkhound", "type": "tag"},
    {"darwin_id": None, "name": "otterhound otter hound", "type": "tag"},
    {"darwin_id": None, "name": "Saluki gazelle hound", "type": "tag"},
    {"darwin_id": None, "name": "Scottish deerhound deerhound", "type": "tag"},
    {"darwin_id": None, "name": "Weimaraner", "type": "tag"},
    {"darwin_id": None, "name": "Staffordshire bullterrier Staffordshire bull terrier", "type": "tag"},
    {
        "darwin_id": None,
        "name": "American Staffordshire terrier Staffordshire terrier American pit bull terrier pit bull terrier",
        "type": "tag",
    },
    {"darwin_id": None, "name": "Bedlington terrier", "type": "tag"},
    {"darwin_id": None, "name": "Border terrier", "type": "tag"},
    {"darwin_id": None, "name": "Kerry blue terrier", "type": "tag"},
    {"darwin_id": None, "name": "Irish terrier", "type": "tag"},
    {"darwin_id": None, "name": "Norfolk terrier", "type": "tag"},
    {"darwin_id": None, "name": "Norwich terrier", "type": "tag"},
    {"darwin_id": None, "name": "Yorkshire terrier", "type": "tag"},
    {"darwin_id": None, "name": "wire-haired fox terrier", "type": "tag"},
    {"darwin_id": None, "name": "Lakeland terrier", "type": "tag"},
    {"darwin_id": None, "name": "Sealyham terrier Sealyham", "type": "tag"},
    {"darwin_id": None, "name": "Airedale Airedale terrier", "type": "tag"},
    {"darwin_id": None, "name": "cairn cairn terrier", "type": "tag"},
    {"darwin_id": None, "name": "Australian terrier", "type": "tag"},
    {"darwin_id": None, "name": "Dandie Dinmont Dandie Dinmont terrier", "type": "tag"},
    {"darwin_id": None, "name": "Boston bull Boston terrier", "type": "tag"},
    {"darwin_id": None, "name": "miniature schnauzer", "type": "tag"},
    {"darwin_id": None, "name": "giant schnauzer", "type": "tag"},
    {"darwin_id": None, "name": "standard schnauzer", "type": "tag"},
    {"darwin_id": None, "name": "Scotch terrier Scottish terrier Scottie", "type": "tag"},
    {"darwin_id": None, "name": "Tibetan terrier chrysanthemum dog", "type": "tag"},
    {"darwin_id": None, "name": "silky terrier Sydney silky", "type": "tag"},
    {"darwin_id": None, "name": "soft-coated wheaten terrier", "type": "tag"},
    {"darwin_id": None, "name": "West Highland white terrier", "type": "tag"},
    {"darwin_id": None, "name": "Lhasa Lhasa apso", "type": "tag"},
    {"darwin_id": None, "name": "flat-coated retriever", "type": "tag"},
    {"darwin_id": None, "name": "curly-coated retriever", "type": "tag"},
    {"darwin_id": None, "name": "golden retriever", "type": "tag"},
    {"darwin_id": None, "name": "Labrador retriever", "type": "tag"},
    {"darwin_id": None, "name": "Chesapeake Bay retriever", "type": "tag"},
    {"darwin_id": None, "name": "German short-haired pointer", "type": "tag"},
    {"darwin_id": None, "name": "vizsla Hungarian pointer", "type": "tag"},
    {"darwin_id": None, "name": "English setter", "type": "tag"},
    {"darwin_id": None, "name": "Irish setter red setter", "type": "tag"},
    {"darwin_id": None, "name": "Gordon setter", "type": "tag"},
    {"darwin_id": None, "name": "Brittany spaniel", "type": "tag"},
    {"darwin_id": None, "name": "clumber clumber spaniel", "type": "tag"},
    {"darwin_id": None, "name": "English springer English springer spaniel", "type": "tag"},
    {"darwin_id": None, "name": "Welsh springer spaniel", "type": "tag"},
    {"darwin_id": None, "name": "cocker spaniel English cocker spaniel cocker", "type": "tag"},
    {"darwin_id": None, "name": "Sussex spaniel", "type": "tag"},
    {"darwin_id": None, "name": "Irish water spaniel", "type": "tag"},
    {"darwin_id": None, "name": "kuvasz", "type": "tag"},
    {"darwin_id": None, "name": "schipperke", "type": "tag"},
    {"darwin_id": None, "name": "groenendael", "type": "tag"},
    {"darwin_id": None, "name": "malinois", "type": "tag"},
    {"darwin_id": None, "name": "briard", "type": "tag"},
    {"darwin_id": None, "name": "kelpie", "type": "tag"},
    {"darwin_id": None, "name": "komondor", "type": "tag"},
    {"darwin_id": None, "name": "Old English sheepdog bobtail", "type": "tag"},
    {"darwin_id": None, "name": "Shetland sheepdog Shetland sheep dog Shetland", "type": "tag"},
    {"darwin_id": None, "name": "collie", "type": "tag"},
    {"darwin_id": None, "name": "Border collie", "type": "tag"},
    {"darwin_id": None, "name": "Bouvier des Flandres Bouviers des Flandres", "type": "tag"},
    {"darwin_id": None, "name": "Rottweiler", "type": "tag"},
    {"darwin_id": None, "name": "German shepherd German shepherd dog German police dog alsatian", "type": "tag"},
    {"darwin_id": None, "name": "Doberman Doberman pinscher", "type": "tag"},
    {"darwin_id": None, "name": "miniature pinscher", "type": "tag"},
    {"darwin_id": None, "name": "Greater Swiss Mountain dog", "type": "tag"},
    {"darwin_id": None, "name": "Bernese mountain dog", "type": "tag"},
    {"darwin_id": None, "name": "Appenzeller", "type": "tag"},
    {"darwin_id": None, "name": "EntleBucher", "type": "tag"},
    {"darwin_id": None, "name": "boxer", "type": "tag"},
    {"darwin_id": None, "name": "bull mastiff", "type": "tag"},
    {"darwin_id": None, "name": "Tibetan mastiff", "type": "tag"},
    {"darwin_id": None, "name": "French bulldog", "type": "tag"},
    {"darwin_id": None, "name": "Great Dane", "type": "tag"},
    {"darwin_id": None, "name": "Saint Bernard St Bernard", "type": "tag"},
    {"darwin_id": None, "name": "Eskimo dog husky", "type": "tag"},
    {"darwin_id": None, "name": "malamute malemute Alaskan malamute", "type": "tag"},
    {"darwin_id": None, "name": "Siberian husky", "type": "tag"},
    {"darwin_id": None, "name": "dalmatian coach dog carriage dog", "type": "tag"},
    {"darwin_id": None, "name": "affenpinscher monkey pinscher monkey dog", "type": "tag"},
    {"darwin_id": None, "name": "basenji", "type": "tag"},
    {"darwin_id": None, "name": "pug pug-dog", "type": "tag"},
    {"darwin_id": None, "name": "Leonberg", "type": "tag"},
    {"darwin_id": None, "name": "Newfoundland Newfoundland dog", "type": "tag"},
    {"darwin_id": None, "name": "Great Pyrenees", "type": "tag"},
    {"darwin_id": None, "name": "Samoyed Samoyede", "type": "tag"},
    {"darwin_id": None, "name": "Pomeranian", "type": "tag"},
    {"darwin_id": None, "name": "chow chow chow", "type": "tag"},
    {"darwin_id": None, "name": "keeshond", "type": "tag"},
    {"darwin_id": None, "name": "Brabancon griffon", "type": "tag"},
    {"darwin_id": None, "name": "Pembroke Pembroke Welsh corgi", "type": "tag"},
    {"darwin_id": None, "name": "Cardigan Cardigan Welsh corgi", "type": "tag"},
    {"darwin_id": None, "name": "toy poodle", "type": "tag"},
    {"darwin_id": None, "name": "miniature poodle", "type": "tag"},
    {"darwin_id": None, "name": "standard poodle", "type": "tag"},
    {"darwin_id": None, "name": "Mexican hairless", "type": "tag"},
    {"darwin_id": None, "name": "timber wolf grey wolf gray wolf Canis lupus", "type": "tag"},
    {"darwin_id": None, "name": "white wolf Arctic wolf Canis lupus tundrarum", "type": "tag"},
    {"darwin_id": None, "name": "red wolf maned wolf Canis rufus Canis niger", "type": "tag"},
    {"darwin_id": None, "name": "coyote prairie wolf brush wolf Canis latrans", "type": "tag"},
    {"darwin_id": None, "name": "dingo warrigal warragal Canis dingo", "type": "tag"},
    {"darwin_id": None, "name": "dhole Cuon alpinus", "type": "tag"},
    {"darwin_id": None, "name": "African hunting dog hyena dog Cape hunting dog Lycaon pictus", "type": "tag"},
    {"darwin_id": None, "name": "hyena hyaena", "type": "tag"},
    {"darwin_id": None, "name": "red fox Vulpes vulpes", "type": "tag"},
    {"darwin_id": None, "name": "kit fox Vulpes macrotis", "type": "tag"},
    {"darwin_id": None, "name": "Arctic fox white fox Alopex lagopus", "type": "tag"},
    {"darwin_id": None, "name": "grey fox gray fox Urocyon cinereoargenteus", "type": "tag"},
    {"darwin_id": None, "name": "tabby tabby cat", "type": "tag"},
    {"darwin_id": None, "name": "tiger cat", "type": "tag"},
    {"darwin_id": None, "name": "Persian cat", "type": "tag"},
    {"darwin_id": None, "name": "Siamese cat Siamese", "type": "tag"},
    {"darwin_id": None, "name": "Egyptian cat", "type": "tag"},
    {"darwin_id": None, "name": "cougar puma catamount mountain lion painter panther Felis concolor", "type": "tag"},
    {"darwin_id": None, "name": "lynx catamount", "type": "tag"},
    {"darwin_id": None, "name": "leopard Panthera pardus", "type": "tag"},
    {"darwin_id": None, "name": "snow leopard ounce Panthera uncia", "type": "tag"},
    {"darwin_id": None, "name": "jaguar panther Panthera onca Felis onca", "type": "tag"},
    {"darwin_id": None, "name": "lion king of beasts Panthera leo", "type": "tag"},
    {"darwin_id": None, "name": "tiger Panthera tigris", "type": "tag"},
    {"darwin_id": None, "name": "cheetah chetah Acinonyx jubatus", "type": "tag"},
    {"darwin_id": None, "name": "brown bear bruin Ursus arctos", "type": "tag"},
    {"darwin_id": None, "name": "American black bear black bear Ursus americanus Euarctos americanus", "type": "tag"},
    {"darwin_id": None, "name": "ice bear polar bear Ursus Maritimus Thalarctos maritimus", "type": "tag"},
    {"darwin_id": None, "name": "sloth bear Melursus ursinus Ursus ursinus", "type": "tag"},
    {"darwin_id": None, "name": "mongoose", "type": "tag"},
    {"darwin_id": None, "name": "meerkat mierkat", "type": "tag"},
    {"darwin_id": None, "name": "tiger beetle", "type": "tag"},
    {"darwin_id": None, "name": "ladybug ladybeetle lady beetle ladybird ladybird beetle", "type": "tag"},
    {"darwin_id": None, "name": "ground beetle carabid beetle", "type": "tag"},
    {"darwin_id": None, "name": "long-horned beetle longicorn longicorn beetle", "type": "tag"},
    {"darwin_id": None, "name": "leaf beetle chrysomelid", "type": "tag"},
    {"darwin_id": None, "name": "dung beetle", "type": "tag"},
    {"darwin_id": None, "name": "rhinoceros beetle", "type": "tag"},
    {"darwin_id": None, "name": "weevil", "type": "tag"},
    {"darwin_id": None, "name": "fly", "type": "tag"},
    {"darwin_id": None, "name": "bee", "type": "tag"},
    {"darwin_id": None, "name": "ant emmet pismire", "type": "tag"},
    {"darwin_id": None, "name": "grasshopper hopper", "type": "tag"},
    {"darwin_id": None, "name": "cricket", "type": "tag"},
    {"darwin_id": None, "name": "walking stick walkingstick stick insect", "type": "tag"},
    {"darwin_id": None, "name": "cockroach roach", "type": "tag"},
    {"darwin_id": None, "name": "mantis mantid", "type": "tag"},
    {"darwin_id": None, "name": "cicada cicala", "type": "tag"},
    {"darwin_id": None, "name": "leafhopper", "type": "tag"},
    {"darwin_id": None, "name": "lacewing lacewing fly", "type": "tag"},
    {
        "darwin_id": None,
        "name": "dragonfly darning needle devils darning needle sewing needle snake feeder snake doctor mosquito hawk skeeter hawk",
        "type": "tag",
    },
    {"darwin_id": None, "name": "damselfly", "type": "tag"},
    {"darwin_id": None, "name": "admiral", "type": "tag"},
    {"darwin_id": None, "name": "ringlet ringlet butterfly", "type": "tag"},
    {"darwin_id": None, "name": "monarch monarch butterfly milkweed butterfly Danaus plexippus", "type": "tag"},
    {"darwin_id": None, "name": "cabbage butterfly", "type": "tag"},
    {"darwin_id": None, "name": "sulphur butterfly sulfur butterfly", "type": "tag"},
    {"darwin_id": None, "name": "lycaenid lycaenid butterfly", "type": "tag"},
    {"darwin_id": None, "name": "starfish sea star", "type": "tag"},
    {"darwin_id": None, "name": "sea urchin", "type": "tag"},
    {"darwin_id": None, "name": "sea cucumber holothurian", "type": "tag"},
    {"darwin_id": None, "name": "wood rabbit cottontail cottontail rabbit", "type": "tag"},
    {"darwin_id": None, "name": "hare", "type": "tag"},
    {"darwin_id": None, "name": "Angora Angora rabbit", "type": "tag"},
    {"darwin_id": None, "name": "hamster", "type": "tag"},
    {"darwin_id": None, "name": "porcupine hedgehog", "type": "tag"},
    {"darwin_id": None, "name": "fox squirrel eastern fox squirrel Sciurus niger", "type": "tag"},
    {"darwin_id": None, "name": "marmot", "type": "tag"},
    {"darwin_id": None, "name": "beaver", "type": "tag"},
    {"darwin_id": None, "name": "guinea pig Cavia cobaya", "type": "tag"},
    {"darwin_id": None, "name": "sorrel", "type": "tag"},
    {"darwin_id": None, "name": "zebra", "type": "tag"},
    {"darwin_id": None, "name": "hog pig grunter squealer Sus scrofa", "type": "tag"},
    {"darwin_id": None, "name": "wild boar boar Sus scrofa", "type": "tag"},
    {"darwin_id": None, "name": "warthog", "type": "tag"},
    {"darwin_id": None, "name": "hippopotamus hippo river horse Hippopotamus amphibius", "type": "tag"},
    {"darwin_id": None, "name": "ox", "type": "tag"},
    {"darwin_id": None, "name": "water buffalo water ox Asiatic buffalo Bubalus bubalis", "type": "tag"},
    {"darwin_id": None, "name": "bison", "type": "tag"},
    {"darwin_id": None, "name": "ram tup", "type": "tag"},
    {
        "darwin_id": None,
        "name": "bighorn bighorn sheep cimarron Rocky Mountain bighorn Rocky Mountain sheep Ovis canadensis",
        "type": "tag",
    },
    {"darwin_id": None, "name": "ibex Capra ibex", "type": "tag"},
    {"darwin_id": None, "name": "hartebeest", "type": "tag"},
    {"darwin_id": None, "name": "impala Aepyceros melampus", "type": "tag"},
    {"darwin_id": None, "name": "gazelle", "type": "tag"},
    {"darwin_id": None, "name": "Arabian camel dromedary Camelus dromedarius", "type": "tag"},
    {"darwin_id": None, "name": "llama", "type": "tag"},
    {"darwin_id": None, "name": "weasel", "type": "tag"},
    {"darwin_id": None, "name": "mink", "type": "tag"},
    {"darwin_id": None, "name": "polecat fitch foulmart foumart Mustela putorius", "type": "tag"},
    {"darwin_id": None, "name": "black-footed ferret ferret Mustela nigripes", "type": "tag"},
    {"darwin_id": None, "name": "otter", "type": "tag"},
    {"darwin_id": None, "name": "skunk polecat wood pussy", "type": "tag"},
    {"darwin_id": None, "name": "badger", "type": "tag"},
    {"darwin_id": None, "name": "armadillo", "type": "tag"},
    {"darwin_id": None, "name": "three-toed sloth ai Bradypus tridactylus", "type": "tag"},
    {"darwin_id": None, "name": "orangutan orang orangutang Pongo pygmaeus", "type": "tag"},
    {"darwin_id": None, "name": "gorilla Gorilla gorilla", "type": "tag"},
    {"darwin_id": None, "name": "chimpanzee chimp Pan troglodytes", "type": "tag"},
    {"darwin_id": None, "name": "gibbon Hylobates lar", "type": "tag"},
    {"darwin_id": None, "name": "siamang Hylobates syndactylus Symphalangus syndactylus", "type": "tag"},
    {"darwin_id": None, "name": "guenon guenon monkey", "type": "tag"},
    {"darwin_id": None, "name": "patas hussar monkey Erythrocebus patas", "type": "tag"},
    {"darwin_id": None, "name": "baboon", "type": "tag"},
    {"darwin_id": None, "name": "macaque", "type": "tag"},
    {"darwin_id": None, "name": "langur", "type": "tag"},
    {"darwin_id": None, "name": "colobus colobus monkey", "type": "tag"},
    {"darwin_id": None, "name": "proboscis monkey Nasalis larvatus", "type": "tag"},
    {"darwin_id": None, "name": "marmoset", "type": "tag"},
    {"darwin_id": None, "name": "capuchin ringtail Cebus capucinus", "type": "tag"},
    {"darwin_id": None, "name": "howler monkey howler", "type": "tag"},
    {"darwin_id": None, "name": "titi titi monkey", "type": "tag"},
    {"darwin_id": None, "name": "spider monkey Ateles geoffroyi", "type": "tag"},
    {"darwin_id": None, "name": "squirrel monkey Saimiri sciureus", "type": "tag"},
    {"darwin_id": None, "name": "Madagascar cat ring-tailed lemur Lemur catta", "type": "tag"},
    {"darwin_id": None, "name": "indri indris Indri indri Indri brevicaudatus", "type": "tag"},
    {"darwin_id": None, "name": "Indian elephant Elephas maximus", "type": "tag"},
    {"darwin_id": None, "name": "African elephant Loxodonta africana", "type": "tag"},
    {"darwin_id": None, "name": "lesser panda red panda panda bear cat cat bear Ailurus fulgens", "type": "tag"},
    {"darwin_id": None, "name": "giant panda panda panda bear coon bear Ailuropoda melanoleuca", "type": "tag"},
    {"darwin_id": None, "name": "barracouta snoek", "type": "tag"},
    {"darwin_id": None, "name": "eel", "type": "tag"},
    {"darwin_id": None, "name": "coho cohoe coho salmon blue jack silver salmon Oncorhynchus kisutch", "type": "tag"},
    {"darwin_id": None, "name": "rock beauty Holocanthus tricolor", "type": "tag"},
    {"darwin_id": None, "name": "anemone fish", "type": "tag"},
    {"darwin_id": None, "name": "sturgeon", "type": "tag"},
    {"darwin_id": None, "name": "gar garfish garpike billfish Lepisosteus osseus", "type": "tag"},
    {"darwin_id": None, "name": "lionfish", "type": "tag"},
    {"darwin_id": None, "name": "puffer pufferfish blowfish globefish", "type": "tag"},
    {"darwin_id": None, "name": "abacus", "type": "tag"},
    {"darwin_id": None, "name": "abaya", "type": "tag"},
    {"darwin_id": None, "name": "academic gown academic robe judges robe", "type": "tag"},
    {"darwin_id": None, "name": "accordion piano accordion squeeze box", "type": "tag"},
    {"darwin_id": None, "name": "acoustic guitar", "type": "tag"},
    {"darwin_id": None, "name": "aircraft carrier carrier flattop attack aircraft carrier", "type": "tag"},
    {"darwin_id": None, "name": "airliner", "type": "tag"},
    {"darwin_id": None, "name": "airship dirigible", "type": "tag"},
    {"darwin_id": None, "name": "altar", "type": "tag"},
    {"darwin_id": None, "name": "ambulance", "type": "tag"},
    {"darwin_id": None, "name": "amphibian amphibious vehicle", "type": "tag"},
    {"darwin_id": None, "name": "analog clock", "type": "tag"},
    {"darwin_id": None, "name": "apiary bee house", "type": "tag"},
    {"darwin_id": None, "name": "apron", "type": "tag"},
    {
        "darwin_id": None,
        "name": "ashcan trash can garbage can wastebin ash bin ash-bin ashbin dustbin trash barrel trash bin",
        "type": "tag",
    },
    {"darwin_id": None, "name": "assault rifle assault gun", "type": "tag"},
    {"darwin_id": None, "name": "backpack back pack knapsack packsack rucksack haversack", "type": "tag"},
    {"darwin_id": None, "name": "bakery bakeshop bakehouse", "type": "tag"},
    {"darwin_id": None, "name": "balance beam beam", "type": "tag"},
    {"darwin_id": None, "name": "balloon", "type": "tag"},
    {"darwin_id": None, "name": "ballpoint ballpoint pen ballpen Biro", "type": "tag"},
    {"darwin_id": None, "name": "Band Aid", "type": "tag"},
    {"darwin_id": None, "name": "banjo", "type": "tag"},
    {"darwin_id": None, "name": "bannister banister balustrade balusters handrail", "type": "tag"},
    {"darwin_id": None, "name": "barbell", "type": "tag"},
    {"darwin_id": None, "name": "barber chair", "type": "tag"},
    {"darwin_id": None, "name": "barbershop", "type": "tag"},
    {"darwin_id": None, "name": "barn", "type": "tag"},
    {"darwin_id": None, "name": "barometer", "type": "tag"},
    {"darwin_id": None, "name": "barrel cask", "type": "tag"},
    {"darwin_id": None, "name": "barrow garden cart lawn cart wheelbarrow", "type": "tag"},
    {"darwin_id": None, "name": "baseball", "type": "tag"},
    {"darwin_id": None, "name": "basketball", "type": "tag"},
    {"darwin_id": None, "name": "bassinet", "type": "tag"},
    {"darwin_id": None, "name": "bassoon", "type": "tag"},
    {"darwin_id": None, "name": "bathing cap swimming cap", "type": "tag"},
    {"darwin_id": None, "name": "bath towel", "type": "tag"},
    {"darwin_id": None, "name": "bathtub bathing tub bath tub", "type": "tag"},
    {
        "darwin_id": None,
        "name": "beach wagon station wagon wagon estate car beach waggon station waggon waggon",
        "type": "tag",
    },
    {"darwin_id": None, "name": "beacon lighthouse beacon light pharos", "type": "tag"},
    {"darwin_id": None, "name": "beaker", "type": "tag"},
    {"darwin_id": None, "name": "bearskin busby shako", "type": "tag"},
    {"darwin_id": None, "name": "beer bottle", "type": "tag"},
    {"darwin_id": None, "name": "beer glass", "type": "tag"},
    {"darwin_id": None, "name": "bell cote bell cot", "type": "tag"},
    {"darwin_id": None, "name": "bib", "type": "tag"},
    {"darwin_id": None, "name": "bicycle-built-for-two tandem bicycle tandem", "type": "tag"},
    {"darwin_id": None, "name": "bikini two-piece", "type": "tag"},
    {"darwin_id": None, "name": "binder ring-binder", "type": "tag"},
    {"darwin_id": None, "name": "binoculars field glasses opera glasses", "type": "tag"},
    {"darwin_id": None, "name": "birdhouse", "type": "tag"},
    {"darwin_id": None, "name": "boathouse", "type": "tag"},
    {"darwin_id": None, "name": "bobsled bobsleigh bob", "type": "tag"},
    {"darwin_id": None, "name": "bolo tie bolo bola tie bola", "type": "tag"},
    {"darwin_id": None, "name": "bonnet poke bonnet", "type": "tag"},
    {"darwin_id": None, "name": "bookcase", "type": "tag"},
    {"darwin_id": None, "name": "bookshop bookstore bookstall", "type": "tag"},
    {"darwin_id": None, "name": "bottlecap", "type": "tag"},
    {"darwin_id": None, "name": "bow", "type": "tag"},
    {"darwin_id": None, "name": "bow tie bow-tie bowtie", "type": "tag"},
    {"darwin_id": None, "name": "brass memorial tablet plaque", "type": "tag"},
    {"darwin_id": None, "name": "brassiere bra bandeau", "type": "tag"},
    {"darwin_id": None, "name": "breakwater groin groyne mole bulwark seawall jetty", "type": "tag"},
    {"darwin_id": None, "name": "breastplate aegis egis", "type": "tag"},
    {"darwin_id": None, "name": "broom", "type": "tag"},
    {"darwin_id": None, "name": "bucket pail", "type": "tag"},
    {"darwin_id": None, "name": "buckle", "type": "tag"},
    {"darwin_id": None, "name": "bulletproof vest", "type": "tag"},
    {"darwin_id": None, "name": "bullet train bullet", "type": "tag"},
    {"darwin_id": None, "name": "butcher shop meat market", "type": "tag"},
    {"darwin_id": None, "name": "cab hack taxi taxicab", "type": "tag"},
    {"darwin_id": None, "name": "caldron cauldron", "type": "tag"},
    {"darwin_id": None, "name": "candle taper wax light", "type": "tag"},
    {"darwin_id": None, "name": "cannon", "type": "tag"},
    {"darwin_id": None, "name": "canoe", "type": "tag"},
    {"darwin_id": None, "name": "can opener tin opener", "type": "tag"},
    {"darwin_id": None, "name": "cardigan", "type": "tag"},
    {"darwin_id": None, "name": "car mirror", "type": "tag"},
    {"darwin_id": None, "name": "carousel carrousel merry-go-round roundabout whirligig", "type": "tag"},
    {"darwin_id": None, "name": "carpenters kit tool kit", "type": "tag"},
    {"darwin_id": None, "name": "carton", "type": "tag"},
    {"darwin_id": None, "name": "car wheel", "type": "tag"},
    {
        "darwin_id": None,
        "name": "cash machine cash dispenser automated teller machine automatic teller machine automated teller automatic teller ATM",
        "type": "tag",
    },
    {"darwin_id": None, "name": "cassette", "type": "tag"},
    {"darwin_id": None, "name": "cassette player", "type": "tag"},
    {"darwin_id": None, "name": "castle", "type": "tag"},
    {"darwin_id": None, "name": "catamaran", "type": "tag"},
    {"darwin_id": None, "name": "CD player", "type": "tag"},
    {"darwin_id": None, "name": "cello violoncello", "type": "tag"},
    {"darwin_id": None, "name": "cellular telephone cellular phone cellphone cell mobile phone", "type": "tag"},
    {"darwin_id": None, "name": "chain", "type": "tag"},
    {"darwin_id": None, "name": "chainlink fence", "type": "tag"},
    {
        "darwin_id": None,
        "name": "chain mail ring mail mail chain armor chain armour ring armor ring armour",
        "type": "tag",
    },
    {"darwin_id": None, "name": "chain saw chainsaw", "type": "tag"},
    {"darwin_id": None, "name": "chest", "type": "tag"},
    {"darwin_id": None, "name": "chiffonier commode", "type": "tag"},
    {"darwin_id": None, "name": "chime bell gong", "type": "tag"},
    {"darwin_id": None, "name": "china cabinet china closet", "type": "tag"},
    {"darwin_id": None, "name": "Christmas stocking", "type": "tag"},
    {"darwin_id": None, "name": "church church building", "type": "tag"},
    {"darwin_id": None, "name": "cinema movie theater movie theatre movie house picture palace", "type": "tag"},
    {"darwin_id": None, "name": "cleaver meat cleaver chopper", "type": "tag"},
    {"darwin_id": None, "name": "cliff dwelling", "type": "tag"},
    {"darwin_id": None, "name": "cloak", "type": "tag"},
    {"darwin_id": None, "name": "clog geta patten sabot", "type": "tag"},
    {"darwin_id": None, "name": "cocktail shaker", "type": "tag"},
    {"darwin_id": None, "name": "coffee mug", "type": "tag"},
    {"darwin_id": None, "name": "coffeepot", "type": "tag"},
    {"darwin_id": None, "name": "coil spiral volute whorl helix", "type": "tag"},
    {"darwin_id": None, "name": "combination lock", "type": "tag"},
    {"darwin_id": None, "name": "computer keyboard keypad", "type": "tag"},
    {"darwin_id": None, "name": "confectionery confectionary candy store", "type": "tag"},
    {"darwin_id": None, "name": "container ship containership container vessel", "type": "tag"},
    {"darwin_id": None, "name": "convertible", "type": "tag"},
    {"darwin_id": None, "name": "corkscrew bottle screw", "type": "tag"},
    {"darwin_id": None, "name": "cornet horn trumpet trump", "type": "tag"},
    {"darwin_id": None, "name": "cowboy boot", "type": "tag"},
    {"darwin_id": None, "name": "cowboy hat ten-gallon hat", "type": "tag"},
    {"darwin_id": None, "name": "cradle", "type": "tag"},
    {"darwin_id": None, "name": "crane", "type": "tag"},
    {"darwin_id": None, "name": "crash helmet", "type": "tag"},
    {"darwin_id": None, "name": "crate", "type": "tag"},
    {"darwin_id": None, "name": "crib cot", "type": "tag"},
    {"darwin_id": None, "name": "Crock Pot", "type": "tag"},
    {"darwin_id": None, "name": "croquet ball", "type": "tag"},
    {"darwin_id": None, "name": "crutch", "type": "tag"},
    {"darwin_id": None, "name": "cuirass", "type": "tag"},
    {"darwin_id": None, "name": "dam dike dyke", "type": "tag"},
    {"darwin_id": None, "name": "desk", "type": "tag"},
    {"darwin_id": None, "name": "desktop computer", "type": "tag"},
    {"darwin_id": None, "name": "dial telephone dial phone", "type": "tag"},
    {"darwin_id": None, "name": "diaper nappy napkin", "type": "tag"},
    {"darwin_id": None, "name": "digital clock", "type": "tag"},
    {"darwin_id": None, "name": "digital watch", "type": "tag"},
    {"darwin_id": None, "name": "dining table board", "type": "tag"},
    {"darwin_id": None, "name": "dishrag dishcloth", "type": "tag"},
    {"darwin_id": None, "name": "dishwasher dish washer dishwashing machine", "type": "tag"},
    {"darwin_id": None, "name": "disk brake disc brake", "type": "tag"},
    {"darwin_id": None, "name": "dock dockage docking facility", "type": "tag"},
    {"darwin_id": None, "name": "dogsled dog sled dog sleigh", "type": "tag"},
    {"darwin_id": None, "name": "dome", "type": "tag"},
    {"darwin_id": None, "name": "doormat welcome mat", "type": "tag"},
    {"darwin_id": None, "name": "drilling platform offshore rig", "type": "tag"},
    {"darwin_id": None, "name": "drum membranophone tympan", "type": "tag"},
    {"darwin_id": None, "name": "drumstick", "type": "tag"},
    {"darwin_id": None, "name": "dumbbell", "type": "tag"},
    {"darwin_id": None, "name": "Dutch oven", "type": "tag"},
    {"darwin_id": None, "name": "electric fan blower", "type": "tag"},
    {"darwin_id": None, "name": "electric guitar", "type": "tag"},
    {"darwin_id": None, "name": "electric locomotive", "type": "tag"},
    {"darwin_id": None, "name": "entertainment center", "type": "tag"},
    {"darwin_id": None, "name": "envelope", "type": "tag"},
    {"darwin_id": None, "name": "espresso maker", "type": "tag"},
    {"darwin_id": None, "name": "face powder", "type": "tag"},
    {"darwin_id": None, "name": "feather boa boa", "type": "tag"},
    {"darwin_id": None, "name": "file file cabinet filing cabinet", "type": "tag"},
    {"darwin_id": None, "name": "fireboat", "type": "tag"},
    {"darwin_id": None, "name": "fire engine fire truck", "type": "tag"},
    {"darwin_id": None, "name": "fire screen fireguard", "type": "tag"},
    {"darwin_id": None, "name": "flagpole flagstaff", "type": "tag"},
    {"darwin_id": None, "name": "flute transverse flute", "type": "tag"},
    {"darwin_id": None, "name": "folding chair", "type": "tag"},
    {"darwin_id": None, "name": "football helmet", "type": "tag"},
    {"darwin_id": None, "name": "forklift", "type": "tag"},
    {"darwin_id": None, "name": "fountain", "type": "tag"},
    {"darwin_id": None, "name": "fountain pen", "type": "tag"},
    {"darwin_id": None, "name": "four-poster", "type": "tag"},
    {"darwin_id": None, "name": "freight car", "type": "tag"},
    {"darwin_id": None, "name": "French horn horn", "type": "tag"},
    {"darwin_id": None, "name": "frying pan frypan skillet", "type": "tag"},
    {"darwin_id": None, "name": "fur coat", "type": "tag"},
    {"darwin_id": None, "name": "garbage truck dustcart", "type": "tag"},
    {"darwin_id": None, "name": "gasmask respirator gas helmet", "type": "tag"},
    {"darwin_id": None, "name": "gas pump gasoline pump petrol pump island dispenser", "type": "tag"},
    {"darwin_id": None, "name": "goblet", "type": "tag"},
    {"darwin_id": None, "name": "go-kart", "type": "tag"},
    {"darwin_id": None, "name": "golf ball", "type": "tag"},
    {"darwin_id": None, "name": "golfcart golf cart", "type": "tag"},
    {"darwin_id": None, "name": "gondola", "type": "tag"},
    {"darwin_id": None, "name": "gong tam-tam", "type": "tag"},
    {"darwin_id": None, "name": "gown", "type": "tag"},
    {"darwin_id": None, "name": "grand piano grand", "type": "tag"},
    {"darwin_id": None, "name": "greenhouse nursery glasshouse", "type": "tag"},
    {"darwin_id": None, "name": "grille radiator grille", "type": "tag"},
    {"darwin_id": None, "name": "grocery store grocery food market market", "type": "tag"},
    {"darwin_id": None, "name": "guillotine", "type": "tag"},
    {"darwin_id": None, "name": "hair slide", "type": "tag"},
    {"darwin_id": None, "name": "hair spray", "type": "tag"},
    {"darwin_id": None, "name": "half track", "type": "tag"},
    {"darwin_id": None, "name": "hammer", "type": "tag"},
    {"darwin_id": None, "name": "hamper", "type": "tag"},
    {"darwin_id": None, "name": "hand blower blow dryer blow drier hair dryer hair drier", "type": "tag"},
    {"darwin_id": None, "name": "hand-held computer hand-held microcomputer", "type": "tag"},
    {"darwin_id": None, "name": "handkerchief hankie hanky hankey", "type": "tag"},
    {"darwin_id": None, "name": "hard disc hard disk fixed disk", "type": "tag"},
    {"darwin_id": None, "name": "harmonica mouth organ harp mouth harp", "type": "tag"},
    {"darwin_id": None, "name": "harp", "type": "tag"},
    {"darwin_id": None, "name": "harvester reaper", "type": "tag"},
    {"darwin_id": None, "name": "hatchet", "type": "tag"},
    {"darwin_id": None, "name": "holster", "type": "tag"},
    {"darwin_id": None, "name": "home theater home theatre", "type": "tag"},
    {"darwin_id": None, "name": "honeycomb", "type": "tag"},
    {"darwin_id": None, "name": "hook claw", "type": "tag"},
    {"darwin_id": None, "name": "hoopskirt crinoline", "type": "tag"},
    {"darwin_id": None, "name": "horizontal bar high bar", "type": "tag"},
    {"darwin_id": None, "name": "horse cart horse-cart", "type": "tag"},
    {"darwin_id": None, "name": "hourglass", "type": "tag"},
    {"darwin_id": None, "name": "iPod", "type": "tag"},
    {"darwin_id": None, "name": "iron smoothing iron", "type": "tag"},
    {"darwin_id": None, "name": "jack-o-lantern", "type": "tag"},
    {"darwin_id": None, "name": "jean blue jean denim", "type": "tag"},
    {"darwin_id": None, "name": "jeep landrover", "type": "tag"},
    {"darwin_id": None, "name": "jersey T-shirt tee shirt", "type": "tag"},
    {"darwin_id": None, "name": "jigsaw puzzle", "type": "tag"},
    {"darwin_id": None, "name": "jinrikisha ricksha rickshaw", "type": "tag"},
    {"darwin_id": None, "name": "joystick", "type": "tag"},
    {"darwin_id": None, "name": "kimono", "type": "tag"},
    {"darwin_id": None, "name": "knee pad", "type": "tag"},
    {"darwin_id": None, "name": "knot", "type": "tag"},
    {"darwin_id": None, "name": "lab coat laboratory coat", "type": "tag"},
    {"darwin_id": None, "name": "ladle", "type": "tag"},
    {"darwin_id": None, "name": "lampshade lamp shade", "type": "tag"},
    {"darwin_id": None, "name": "laptop laptop computer", "type": "tag"},
    {"darwin_id": None, "name": "lawn mower mower", "type": "tag"},
    {"darwin_id": None, "name": "lens cap lens cover", "type": "tag"},
    {"darwin_id": None, "name": "letter opener paper knife paperknife", "type": "tag"},
    {"darwin_id": None, "name": "library", "type": "tag"},
    {"darwin_id": None, "name": "lifeboat", "type": "tag"},
    {"darwin_id": None, "name": "lighter light igniter ignitor", "type": "tag"},
    {"darwin_id": None, "name": "limousine limo", "type": "tag"},
    {"darwin_id": None, "name": "liner ocean liner", "type": "tag"},
    {"darwin_id": None, "name": "lipstick lip rouge", "type": "tag"},
    {"darwin_id": None, "name": "Loafer", "type": "tag"},
    {"darwin_id": None, "name": "lotion", "type": "tag"},
    {"darwin_id": None, "name": "loudspeaker speaker speaker unit loudspeaker system speaker system", "type": "tag"},
    {"darwin_id": None, "name": "loupe jewelers loupe", "type": "tag"},
    {"darwin_id": None, "name": "lumbermill sawmill", "type": "tag"},
    {"darwin_id": None, "name": "magnetic compass", "type": "tag"},
    {"darwin_id": None, "name": "mailbag postbag", "type": "tag"},
    {"darwin_id": None, "name": "mailbox letter box", "type": "tag"},
    {"darwin_id": None, "name": "maillot", "type": "tag"},
    {"darwin_id": None, "name": "maillot tank suit", "type": "tag"},
    {"darwin_id": None, "name": "manhole cover", "type": "tag"},
    {"darwin_id": None, "name": "maraca", "type": "tag"},
    {"darwin_id": None, "name": "marimba xylophone", "type": "tag"},
    {"darwin_id": None, "name": "mask", "type": "tag"},
    {"darwin_id": None, "name": "matchstick", "type": "tag"},
    {"darwin_id": None, "name": "maypole", "type": "tag"},
    {"darwin_id": None, "name": "maze labyrinth", "type": "tag"},
    {"darwin_id": None, "name": "measuring cup", "type": "tag"},
    {"darwin_id": None, "name": "medicine chest medicine cabinet", "type": "tag"},
    {"darwin_id": None, "name": "megalith megalithic structure", "type": "tag"},
    {"darwin_id": None, "name": "microphone mike", "type": "tag"},
    {"darwin_id": None, "name": "microwave microwave oven", "type": "tag"},
    {"darwin_id": None, "name": "military uniform", "type": "tag"},
    {"darwin_id": None, "name": "milk can", "type": "tag"},
    {"darwin_id": None, "name": "minibus", "type": "tag"},
    {"darwin_id": None, "name": "miniskirt mini", "type": "tag"},
    {"darwin_id": None, "name": "minivan", "type": "tag"},
    {"darwin_id": None, "name": "missile", "type": "tag"},
    {"darwin_id": None, "name": "mitten", "type": "tag"},
    {"darwin_id": None, "name": "mixing bowl", "type": "tag"},
    {"darwin_id": None, "name": "mobile home manufactured home", "type": "tag"},
    {"darwin_id": None, "name": "Model T", "type": "tag"},
    {"darwin_id": None, "name": "modem", "type": "tag"},
    {"darwin_id": None, "name": "monastery", "type": "tag"},
    {"darwin_id": None, "name": "monitor", "type": "tag"},
    {"darwin_id": None, "name": "moped", "type": "tag"},
    {"darwin_id": None, "name": "mortar", "type": "tag"},
    {"darwin_id": None, "name": "mortarboard", "type": "tag"},
    {"darwin_id": None, "name": "mosque", "type": "tag"},
    {"darwin_id": None, "name": "mosquito net", "type": "tag"},
    {"darwin_id": None, "name": "motor scooter scooter", "type": "tag"},
    {"darwin_id": None, "name": "mountain bike all-terrain bike off-roader", "type": "tag"},
    {"darwin_id": None, "name": "mountain tent", "type": "tag"},
    {"darwin_id": None, "name": "mouse computer mouse", "type": "tag"},
    {"darwin_id": None, "name": "mousetrap", "type": "tag"},
    {"darwin_id": None, "name": "moving van", "type": "tag"},
    {"darwin_id": None, "name": "muzzle", "type": "tag"},
    {"darwin_id": None, "name": "nail", "type": "tag"},
    {"darwin_id": None, "name": "neck brace", "type": "tag"},
    {"darwin_id": None, "name": "necklace", "type": "tag"},
    {"darwin_id": None, "name": "nipple", "type": "tag"},
    {"darwin_id": None, "name": "notebook notebook computer", "type": "tag"},
    {"darwin_id": None, "name": "obelisk", "type": "tag"},
    {"darwin_id": None, "name": "oboe hautboy hautbois", "type": "tag"},
    {"darwin_id": None, "name": "ocarina sweet potato", "type": "tag"},
    {"darwin_id": None, "name": "odometer hodometer mileometer milometer", "type": "tag"},
    {"darwin_id": None, "name": "oil filter", "type": "tag"},
    {"darwin_id": None, "name": "organ pipe organ", "type": "tag"},
    {"darwin_id": None, "name": "oscilloscope scope cathode-ray oscilloscope CRO", "type": "tag"},
    {"darwin_id": None, "name": "overskirt", "type": "tag"},
    {"darwin_id": None, "name": "oxcart", "type": "tag"},
    {"darwin_id": None, "name": "oxygen mask", "type": "tag"},
    {"darwin_id": None, "name": "packet", "type": "tag"},
    {"darwin_id": None, "name": "paddle boat paddle", "type": "tag"},
    {"darwin_id": None, "name": "paddlewheel paddle wheel", "type": "tag"},
    {"darwin_id": None, "name": "padlock", "type": "tag"},
    {"darwin_id": None, "name": "paintbrush", "type": "tag"},
    {"darwin_id": None, "name": "pajama pyjama pjs jammies", "type": "tag"},
    {"darwin_id": None, "name": "palace", "type": "tag"},
    {"darwin_id": None, "name": "panpipe pandean pipe syrinx", "type": "tag"},
    {"darwin_id": None, "name": "paper towel", "type": "tag"},
    {"darwin_id": None, "name": "parachute chute", "type": "tag"},
    {"darwin_id": None, "name": "parallel bars bars", "type": "tag"},
    {"darwin_id": None, "name": "park bench", "type": "tag"},
    {"darwin_id": None, "name": "parking meter", "type": "tag"},
    {"darwin_id": None, "name": "passenger car coach carriage", "type": "tag"},
    {"darwin_id": None, "name": "patio terrace", "type": "tag"},
    {"darwin_id": None, "name": "pay-phone pay-station", "type": "tag"},
    {"darwin_id": None, "name": "pedestal plinth footstall", "type": "tag"},
    {"darwin_id": None, "name": "pencil box pencil case", "type": "tag"},
    {"darwin_id": None, "name": "pencil sharpener", "type": "tag"},
    {"darwin_id": None, "name": "perfume essence", "type": "tag"},
    {"darwin_id": None, "name": "Petri dish", "type": "tag"},
    {"darwin_id": None, "name": "photocopier", "type": "tag"},
    {"darwin_id": None, "name": "pick plectrum plectron", "type": "tag"},
    {"darwin_id": None, "name": "pickelhaube", "type": "tag"},
    {"darwin_id": None, "name": "picket fence paling", "type": "tag"},
    {"darwin_id": None, "name": "pickup pickup truck", "type": "tag"},
    {"darwin_id": None, "name": "pier", "type": "tag"},
    {"darwin_id": None, "name": "piggy bank penny bank", "type": "tag"},
    {"darwin_id": None, "name": "pill bottle", "type": "tag"},
    {"darwin_id": None, "name": "pillow", "type": "tag"},
    {"darwin_id": None, "name": "ping-pong ball", "type": "tag"},
    {"darwin_id": None, "name": "pinwheel", "type": "tag"},
    {"darwin_id": None, "name": "pirate pirate ship", "type": "tag"},
    {"darwin_id": None, "name": "pitcher ewer", "type": "tag"},
    {"darwin_id": None, "name": "plane carpenters plane woodworking plane", "type": "tag"},
    {"darwin_id": None, "name": "planetarium", "type": "tag"},
    {"darwin_id": None, "name": "plastic bag", "type": "tag"},
    {"darwin_id": None, "name": "plate rack", "type": "tag"},
    {"darwin_id": None, "name": "plow plough", "type": "tag"},
    {"darwin_id": None, "name": "plunger plumbers helper", "type": "tag"},
    {"darwin_id": None, "name": "Polaroid camera Polaroid Land camera", "type": "tag"},
    {"darwin_id": None, "name": "pole", "type": "tag"},
    {"darwin_id": None, "name": "police van police wagon paddy wagon patrol wagon wagon black Maria", "type": "tag"},
    {"darwin_id": None, "name": "poncho", "type": "tag"},
    {"darwin_id": None, "name": "pool table billiard table snooker table", "type": "tag"},
    {"darwin_id": None, "name": "pop bottle soda bottle", "type": "tag"},
    {"darwin_id": None, "name": "pot flowerpot", "type": "tag"},
    {"darwin_id": None, "name": "potters wheel", "type": "tag"},
    {"darwin_id": None, "name": "power drill", "type": "tag"},
    {"darwin_id": None, "name": "prayer rug prayer mat", "type": "tag"},
    {"darwin_id": None, "name": "printer", "type": "tag"},
    {"darwin_id": None, "name": "prison prison house", "type": "tag"},
    {"darwin_id": None, "name": "projectile missile", "type": "tag"},
    {"darwin_id": None, "name": "projector", "type": "tag"},
    {"darwin_id": None, "name": "puck hockey puck", "type": "tag"},
    {"darwin_id": None, "name": "punching bag punch bag punching ball punchball", "type": "tag"},
    {"darwin_id": None, "name": "purse", "type": "tag"},
    {"darwin_id": None, "name": "quill quill pen", "type": "tag"},
    {"darwin_id": None, "name": "quilt comforter comfort puff", "type": "tag"},
    {"darwin_id": None, "name": "racer race car racing car", "type": "tag"},
    {"darwin_id": None, "name": "racket racquet", "type": "tag"},
    {"darwin_id": None, "name": "radiator", "type": "tag"},
    {"darwin_id": None, "name": "radio wireless", "type": "tag"},
    {"darwin_id": None, "name": "radio telescope radio reflector", "type": "tag"},
    {"darwin_id": None, "name": "rain barrel", "type": "tag"},
    {"darwin_id": None, "name": "recreational vehicle RV R.V.", "type": "tag"},
    {"darwin_id": None, "name": "reel", "type": "tag"},
    {"darwin_id": None, "name": "reflex camera", "type": "tag"},
    {"darwin_id": None, "name": "refrigerator icebox", "type": "tag"},
    {"darwin_id": None, "name": "remote control remote", "type": "tag"},
    {"darwin_id": None, "name": "restaurant eating house eating place eatery", "type": "tag"},
    {"darwin_id": None, "name": "revolver six-gun six-shooter", "type": "tag"},
    {"darwin_id": None, "name": "rifle", "type": "tag"},
    {"darwin_id": None, "name": "rocking chair rocker", "type": "tag"},
    {"darwin_id": None, "name": "rotisserie", "type": "tag"},
    {"darwin_id": None, "name": "rubber eraser rubber pencil eraser", "type": "tag"},
    {"darwin_id": None, "name": "rugby ball", "type": "tag"},
    {"darwin_id": None, "name": "rule ruler", "type": "tag"},
    {"darwin_id": None, "name": "running shoe", "type": "tag"},
    {"darwin_id": None, "name": "safe", "type": "tag"},
    {"darwin_id": None, "name": "safety pin", "type": "tag"},
    {"darwin_id": None, "name": "saltshaker salt shaker", "type": "tag"},
    {"darwin_id": None, "name": "sandal", "type": "tag"},
    {"darwin_id": None, "name": "sarong", "type": "tag"},
    {"darwin_id": None, "name": "sax saxophone", "type": "tag"},
    {"darwin_id": None, "name": "scabbard", "type": "tag"},
    {"darwin_id": None, "name": "scale weighing machine", "type": "tag"},
    {"darwin_id": None, "name": "school bus", "type": "tag"},
    {"darwin_id": None, "name": "schooner", "type": "tag"},
    {"darwin_id": None, "name": "scoreboard", "type": "tag"},
    {"darwin_id": None, "name": "screen CRT screen", "type": "tag"},
    {"darwin_id": None, "name": "screw", "type": "tag"},
    {"darwin_id": None, "name": "screwdriver", "type": "tag"},
    {"darwin_id": None, "name": "seat belt seatbelt", "type": "tag"},
    {"darwin_id": None, "name": "sewing machine", "type": "tag"},
    {"darwin_id": None, "name": "shield buckler", "type": "tag"},
    {"darwin_id": None, "name": "shoe shop shoe-shop shoe store", "type": "tag"},
    {"darwin_id": None, "name": "shoji", "type": "tag"},
    {"darwin_id": None, "name": "shopping basket", "type": "tag"},
    {"darwin_id": None, "name": "shopping cart", "type": "tag"},
    {"darwin_id": None, "name": "shovel", "type": "tag"},
    {"darwin_id": None, "name": "shower cap", "type": "tag"},
    {"darwin_id": None, "name": "shower curtain", "type": "tag"},
    {"darwin_id": None, "name": "ski", "type": "tag"},
    {"darwin_id": None, "name": "ski mask", "type": "tag"},
    {"darwin_id": None, "name": "sleeping bag", "type": "tag"},
    {"darwin_id": None, "name": "slide rule slipstick", "type": "tag"},
    {"darwin_id": None, "name": "sliding door", "type": "tag"},
    {"darwin_id": None, "name": "slot one-armed bandit", "type": "tag"},
    {"darwin_id": None, "name": "snorkel", "type": "tag"},
    {"darwin_id": None, "name": "snowmobile", "type": "tag"},
    {"darwin_id": None, "name": "snowplow snowplough", "type": "tag"},
    {"darwin_id": None, "name": "soap dispenser", "type": "tag"},
    {"darwin_id": None, "name": "soccer ball", "type": "tag"},
    {"darwin_id": None, "name": "sock", "type": "tag"},
    {"darwin_id": None, "name": "solar dish solar collector solar furnace", "type": "tag"},
    {"darwin_id": None, "name": "sombrero", "type": "tag"},
    {"darwin_id": None, "name": "soup bowl", "type": "tag"},
    {"darwin_id": None, "name": "space bar", "type": "tag"},
    {"darwin_id": None, "name": "space heater", "type": "tag"},
    {"darwin_id": None, "name": "space shuttle", "type": "tag"},
    {"darwin_id": None, "name": "spatula", "type": "tag"},
    {"darwin_id": None, "name": "speedboat", "type": "tag"},
    {"darwin_id": None, "name": "spider web spiders web", "type": "tag"},
    {"darwin_id": None, "name": "spindle", "type": "tag"},
    {"darwin_id": None, "name": "sports car sport car", "type": "tag"},
    {"darwin_id": None, "name": "spotlight spot", "type": "tag"},
    {"darwin_id": None, "name": "stage", "type": "tag"},
    {"darwin_id": None, "name": "steam locomotive", "type": "tag"},
    {"darwin_id": None, "name": "steel arch bridge", "type": "tag"},
    {"darwin_id": None, "name": "steel drum", "type": "tag"},
    {"darwin_id": None, "name": "stethoscope", "type": "tag"},
    {"darwin_id": None, "name": "stole", "type": "tag"},
    {"darwin_id": None, "name": "stone wall", "type": "tag"},
    {"darwin_id": None, "name": "stopwatch stop watch", "type": "tag"},
    {"darwin_id": None, "name": "stove", "type": "tag"},
    {"darwin_id": None, "name": "strainer", "type": "tag"},
    {"darwin_id": None, "name": "streetcar tram tramcar trolley trolley car", "type": "tag"},
    {"darwin_id": None, "name": "stretcher", "type": "tag"},
    {"darwin_id": None, "name": "studio couch day bed", "type": "tag"},
    {"darwin_id": None, "name": "stupa tope", "type": "tag"},
    {"darwin_id": None, "name": "submarine pigboat sub U-boat", "type": "tag"},
    {"darwin_id": None, "name": "suit suit of clothes", "type": "tag"},
    {"darwin_id": None, "name": "sundial", "type": "tag"},
    {"darwin_id": None, "name": "sunglass", "type": "tag"},
    {"darwin_id": None, "name": "sunglasses dark glasses shades", "type": "tag"},
    {"darwin_id": None, "name": "sunscreen sunblock sun blocker", "type": "tag"},
    {"darwin_id": None, "name": "suspension bridge", "type": "tag"},
    {"darwin_id": None, "name": "swab swob mop", "type": "tag"},
    {"darwin_id": None, "name": "sweatshirt", "type": "tag"},
    {"darwin_id": None, "name": "swimming trunks bathing trunks", "type": "tag"},
    {"darwin_id": None, "name": "swing", "type": "tag"},
    {"darwin_id": None, "name": "switch electric switch electrical switch", "type": "tag"},
    {"darwin_id": None, "name": "syringe", "type": "tag"},
    {"darwin_id": None, "name": "table lamp", "type": "tag"},
    {"darwin_id": None, "name": "tank army tank armored combat vehicle armoured combat vehicle", "type": "tag"},
    {"darwin_id": None, "name": "tape player", "type": "tag"},
    {"darwin_id": None, "name": "teapot", "type": "tag"},
    {"darwin_id": None, "name": "teddy teddy bear", "type": "tag"},
    {"darwin_id": None, "name": "television television system", "type": "tag"},
    {"darwin_id": None, "name": "tennis ball", "type": "tag"},
    {"darwin_id": None, "name": "thatch thatched roof", "type": "tag"},
    {"darwin_id": None, "name": "theater curtain theatre curtain", "type": "tag"},
    {"darwin_id": None, "name": "thimble", "type": "tag"},
    {"darwin_id": None, "name": "thresher thrasher threshing machine", "type": "tag"},
    {"darwin_id": None, "name": "throne", "type": "tag"},
    {"darwin_id": None, "name": "tile roof", "type": "tag"},
    {"darwin_id": None, "name": "toaster", "type": "tag"},
    {"darwin_id": None, "name": "tobacco shop tobacconist shop tobacconist", "type": "tag"},
    {"darwin_id": None, "name": "toilet seat", "type": "tag"},
    {"darwin_id": None, "name": "torch", "type": "tag"},
    {"darwin_id": None, "name": "totem pole", "type": "tag"},
    {"darwin_id": None, "name": "tow truck tow car wrecker", "type": "tag"},
    {"darwin_id": None, "name": "toyshop", "type": "tag"},
    {"darwin_id": None, "name": "tractor", "type": "tag"},
    {"darwin_id": None, "name": "trailer truck tractor trailer trucking rig rig articulated lorry semi", "type": "tag"},
    {"darwin_id": None, "name": "tray", "type": "tag"},
    {"darwin_id": None, "name": "trench coat", "type": "tag"},
    {"darwin_id": None, "name": "tricycle trike velocipede", "type": "tag"},
    {"darwin_id": None, "name": "trimaran", "type": "tag"},
    {"darwin_id": None, "name": "tripod", "type": "tag"},
    {"darwin_id": None, "name": "triumphal arch", "type": "tag"},
    {"darwin_id": None, "name": "trolleybus trolley coach trackless trolley", "type": "tag"},
    {"darwin_id": None, "name": "trombone", "type": "tag"},
    {"darwin_id": None, "name": "tub vat", "type": "tag"},
    {"darwin_id": None, "name": "turnstile", "type": "tag"},
    {"darwin_id": None, "name": "typewriter keyboard", "type": "tag"},
    {"darwin_id": None, "name": "umbrella", "type": "tag"},
    {"darwin_id": None, "name": "unicycle monocycle", "type": "tag"},
    {"darwin_id": None, "name": "upright upright piano", "type": "tag"},
    {"darwin_id": None, "name": "vacuum vacuum cleaner", "type": "tag"},
    {"darwin_id": None, "name": "vase", "type": "tag"},
    {"darwin_id": None, "name": "vault", "type": "tag"},
    {"darwin_id": None, "name": "velvet", "type": "tag"},
    {"darwin_id": None, "name": "vending machine", "type": "tag"},
    {"darwin_id": None, "name": "vestment", "type": "tag"},
    {"darwin_id": None, "name": "viaduct", "type": "tag"},
    {"darwin_id": None, "name": "violin fiddle", "type": "tag"},
    {"darwin_id": None, "name": "volleyball", "type": "tag"},
    {"darwin_id": None, "name": "waffle iron", "type": "tag"},
    {"darwin_id": None, "name": "wall clock", "type": "tag"},
    {"darwin_id": None, "name": "wallet billfold notecase pocketbook", "type": "tag"},
    {"darwin_id": None, "name": "wardrobe closet press", "type": "tag"},
    {"darwin_id": None, "name": "warplane military plane", "type": "tag"},
    {"darwin_id": None, "name": "washbasin handbasin washbowl lavabo wash-hand basin", "type": "tag"},
    {"darwin_id": None, "name": "washer automatic washer washing machine", "type": "tag"},
    {"darwin_id": None, "name": "water bottle", "type": "tag"},
    {"darwin_id": None, "name": "water jug", "type": "tag"},
    {"darwin_id": None, "name": "water tower", "type": "tag"},
    {"darwin_id": None, "name": "whiskey jug", "type": "tag"},
    {"darwin_id": None, "name": "whistle", "type": "tag"},
    {"darwin_id": None, "name": "wig", "type": "tag"},
    {"darwin_id": None, "name": "window screen", "type": "tag"},
    {"darwin_id": None, "name": "window shade", "type": "tag"},
    {"darwin_id": None, "name": "Windsor tie", "type": "tag"},
    {"darwin_id": None, "name": "wine bottle", "type": "tag"},
    {"darwin_id": None, "name": "wing", "type": "tag"},
    {"darwin_id": None, "name": "wok", "type": "tag"},
    {"darwin_id": None, "name": "wooden spoon", "type": "tag"},
    {"darwin_id": None, "name": "wool woolen woollen", "type": "tag"},
    {"darwin_id": None, "name": "worm fence snake fence snake-rail fence Virginia fence", "type": "tag"},
    {"darwin_id": None, "name": "wreck", "type": "tag"},
    {"darwin_id": None, "name": "yawl", "type": "tag"},
    {"darwin_id": None, "name": "yurt", "type": "tag"},
    {"darwin_id": None, "name": "web site website internet site site", "type": "tag"},
    {"darwin_id": None, "name": "comic book", "type": "tag"},
    {"darwin_id": None, "name": "crossword puzzle crossword", "type": "tag"},
    {"darwin_id": None, "name": "street sign", "type": "tag"},
    {"darwin_id": None, "name": "traffic light traffic signal stoplight", "type": "tag"},
    {"darwin_id": None, "name": "book jacket dust cover dust jacket dust wrapper", "type": "tag"},
    {"darwin_id": None, "name": "menu", "type": "tag"},
    {"darwin_id": None, "name": "plate", "type": "tag"},
    {"darwin_id": None, "name": "guacamole", "type": "tag"},
    {"darwin_id": None, "name": "consomme", "type": "tag"},
    {"darwin_id": None, "name": "hot pot hotpot", "type": "tag"},
    {"darwin_id": None, "name": "trifle", "type": "tag"},
    {"darwin_id": None, "name": "ice cream icecream", "type": "tag"},
    {"darwin_id": None, "name": "ice lolly lolly lollipop popsicle", "type": "tag"},
    {"darwin_id": None, "name": "French loaf", "type": "tag"},
    {"darwin_id": None, "name": "bagel beigel", "type": "tag"},
    {"darwin_id": None, "name": "pretzel", "type": "tag"},
    {"darwin_id": None, "name": "cheeseburger", "type": "tag"},
    {"darwin_id": None, "name": "hotdog hot dog red hot", "type": "tag"},
    {"darwin_id": None, "name": "mashed potato", "type": "tag"},
    {"darwin_id": None, "name": "head cabbage", "type": "tag"},
    {"darwin_id": None, "name": "broccoli", "type": "tag"},
    {"darwin_id": None, "name": "cauliflower", "type": "tag"},
    {"darwin_id": None, "name": "zucchini courgette", "type": "tag"},
    {"darwin_id": None, "name": "spaghetti squash", "type": "tag"},
    {"darwin_id": None, "name": "acorn squash", "type": "tag"},
    {"darwin_id": None, "name": "butternut squash", "type": "tag"},
    {"darwin_id": None, "name": "cucumber cuke", "type": "tag"},
    {"darwin_id": None, "name": "artichoke globe artichoke", "type": "tag"},
    {"darwin_id": None, "name": "bell pepper", "type": "tag"},
    {"darwin_id": None, "name": "cardoon", "type": "tag"},
    {"darwin_id": None, "name": "mushroom", "type": "tag"},
    {"darwin_id": None, "name": "Granny Smith", "type": "tag"},
    {"darwin_id": None, "name": "strawberry", "type": "tag"},
    {"darwin_id": None, "name": "orange", "type": "tag"},
    {"darwin_id": None, "name": "lemon", "type": "tag"},
    {"darwin_id": None, "name": "fig", "type": "tag"},
    {"darwin_id": None, "name": "pineapple ananas", "type": "tag"},
    {"darwin_id": None, "name": "banana", "type": "tag"},
    {"darwin_id": None, "name": "jackfruit jak jack", "type": "tag"},
    {"darwin_id": None, "name": "custard apple", "type": "tag"},
    {"darwin_id": None, "name": "pomegranate", "type": "tag"},
    {"darwin_id": None, "name": "hay", "type": "tag"},
    {"darwin_id": None, "name": "carbonara", "type": "tag"},
    {"darwin_id": None, "name": "chocolate sauce chocolate syrup", "type": "tag"},
    {"darwin_id": None, "name": "dough", "type": "tag"},
    {"darwin_id": None, "name": "meat loaf meatloaf", "type": "tag"},
    {"darwin_id": None, "name": "pizza pizza pie", "type": "tag"},
    {"darwin_id": None, "name": "potpie", "type": "tag"},
    {"darwin_id": None, "name": "burrito", "type": "tag"},
    {"darwin_id": None, "name": "red wine", "type": "tag"},
    {"darwin_id": None, "name": "espresso", "type": "tag"},
    {"darwin_id": None, "name": "cup", "type": "tag"},
    {"darwin_id": None, "name": "eggnog", "type": "tag"},
    {"darwin_id": None, "name": "alp", "type": "tag"},
    {"darwin_id": None, "name": "bubble", "type": "tag"},
    {"darwin_id": None, "name": "cliff drop drop-off", "type": "tag"},
    {"darwin_id": None, "name": "coral reef", "type": "tag"},
    {"darwin_id": None, "name": "geyser", "type": "tag"},
    {"darwin_id": None, "name": "lakeside lakeshore", "type": "tag"},
    {"darwin_id": None, "name": "promontory headland head foreland", "type": "tag"},
    {"darwin_id": None, "name": "sandbar sand bar", "type": "tag"},
    {"darwin_id": None, "name": "seashore coast seacoast sea-coast", "type": "tag"},
    {"darwin_id": None, "name": "valley vale", "type": "tag"},
    {"darwin_id": None, "name": "volcano", "type": "tag"},
    {"darwin_id": None, "name": "ballplayer baseball player", "type": "tag"},
    {"darwin_id": None, "name": "groom bridegroom", "type": "tag"},
    {"darwin_id": None, "name": "scuba diver", "type": "tag"},
    {"darwin_id": None, "name": "rapeseed", "type": "tag"},
    {"darwin_id": None, "name": "daisy", "type": "tag"},
    {
        "darwin_id": None,
        "name": "yellow ladys slipper yellow lady-slipper Cypripedium calceolus Cypripedium parviflorum",
        "type": "tag",
    },
    {"darwin_id": None, "name": "corn", "type": "tag"},
    {"darwin_id": None, "name": "acorn", "type": "tag"},
    {"darwin_id": None, "name": "hip rose hip rosehip", "type": "tag"},
    {"darwin_id": None, "name": "buckeye horse chestnut conker", "type": "tag"},
    {"darwin_id": None, "name": "coral fungus", "type": "tag"},
    {"darwin_id": None, "name": "agaric", "type": "tag"},
    {"darwin_id": None, "name": "gyromitra", "type": "tag"},
    {"darwin_id": None, "name": "stinkhorn carrion fungus", "type": "tag"},
    {"darwin_id": None, "name": "earthstar", "type": "tag"},
    {
        "darwin_id": None,
        "name": "hen-of-the-woods hen of the woods Polyporus frondosus Grifola frondosa",
        "type": "tag",
    },
    {"darwin_id": None, "name": "bolete", "type": "tag"},
    {"darwin_id": None, "name": "ear spike capitulum", "type": "tag"},
    {"darwin_id": None, "name": "toilet tissue toilet paper bathroom tissue", "type": "tag"},
]
